Api documentation
timokau/prefq pull request #47
Opened 2023-11-27 14:15 UTC by patrickab

This pull request introduces first a first impression about how the content of our API-Documentation could look like. However, a standard documentation scheme as mentioned in #38 should be applied. For REST API's, such as our flask server, [Swagger](https://swagger.io/resources/articles/documenting-apis-with-swagger/) might be a good solution.

2023-11-27 15:18 UTC, timokau commented on prefq/templates/web_interface.html
> +
This was already merged in #45. Could you rebase the PR on latest master?

2023-12-01 15:44 UTC, timokau requested changes
Looks good! Just one minor nitpick regarding the file extension change.

2023-12-01 16:10 UTC, patrickab commented on prefq/server.py
> +    right_filename = query_id + "-right.mpeg"
good point! this is just a relict related to #24

2023-12-01 16:14 UTC, patrickab commented on prefq/server.py
> +    right_filename = query_id + "-right.mpeg"
i've just reverted these changes in a interactive rebase

2023-12-01 16:23 UTC, timokau approved these changes
Great, thank you!

2023-12-01 16:23 UTC, merged