Introduce Query Client Class
timokau/prefq pull request #58
Opened 2024-01-10 11:10 UTC by patrickab

2024-01-11 12:54 UTC, timokau requested changes
Looks good! I just have two minor suggestions.

2024-01-11 12:54 UTC, timokau commented on prefq/examples/imitation_preference_comparisons.py
> +from prefq.examples.queryclient import QueryClient
I think the `queryclient` module should not be part of `examples`. I'd also prefer to use an underscore in the name: I think  `prefq.query_client` would be good.

2024-01-11 12:54 UTC, timokau commented on prefq/examples/queryclient.py
> +        """
Please reformat this to adhere to the "single-line summary first, then details" style of docstring (similar to a commit message).

2024-01-15 12:27 UTC, patrickab commented
ready to be reviewed

2024-01-15 18:00 UTC, timokau approved these changes
Thank you!

2024-01-15 18:00 UTC, merged